/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.northeastern.UserInterface.SysAdmin;

import edu.northeastern.Business.DatabaseUtil.DB4OUtil;
import edu.northeastern.Business.EcoSystem;
import edu.northeastern.UserInterface.UserLogin;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author azizvohra
 */
public class SysAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminWorkAreaJPanel
     */
    JPanel container;
    EcoSystem ecosystem;
    // private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public SysAdminWorkAreaJPanel(JPanel container, EcoSystem ecosystem) {
        initComponents();
        // ecosystem = dB4OUtil.retrieveSystem();
        this.setSize(1920, 1080);
        this.container = container;
        this.ecosystem = ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pharmaButton = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        emergencyButton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nonProfitButton = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        governmentButton = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hospitalButton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 36, 41));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Welcome Admin, Here you can manage all your Organizations ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 1410, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("LOGOUT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 110, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons8-supplement-bottle-96.png"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 87));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText(" Pharmacy ");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 150, -1));

        pharmaButton.setBackground(new java.awt.Color(35, 36, 41));
        pharmaButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pharmaButton.setForeground(new java.awt.Color(255, 255, 255));
        pharmaButton.setText("Manage");
        pharmaButton.setBorder(null);
        pharmaButton.setFocusPainted(false);
        pharmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmaButtonActionPerformed(evt);
            }
        });
        jPanel4.add(pharmaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 180, 40));

        jLabel26.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 102));
        jLabel26.setText("Orgnaization  ");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 320, 290));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons8-siren-96.png"))); // NOI18N
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 87));

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText(" Emergency ");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 150, -1));

        emergencyButton.setBackground(new java.awt.Color(35, 36, 41));
        emergencyButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        emergencyButton.setForeground(new java.awt.Color(255, 255, 255));
        emergencyButton.setText("Manage");
        emergencyButton.setBorder(null);
        emergencyButton.setFocusPainted(false);
        emergencyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyButtonActionPerformed(evt);
            }
        });
        jPanel6.add(emergencyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 180, 40));

        jLabel25.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 102));
        jLabel25.setText("Orgnaization  ");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 180, 320, 290));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons8-world-health-organization-96.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 87));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText(" Non-Profit ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 140, -1));

        nonProfitButton.setBackground(new java.awt.Color(35, 36, 41));
        nonProfitButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        nonProfitButton.setForeground(new java.awt.Color(255, 255, 255));
        nonProfitButton.setText("Manage");
        nonProfitButton.setBorder(null);
        nonProfitButton.setFocusPainted(false);
        nonProfitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonProfitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(nonProfitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 180, 40));

        jLabel27.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 102));
        jLabel27.setText("Orgnaization  ");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 530, 320, 290));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons8-city-hall-96.png"))); // NOI18N
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 87));

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Government ");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 170, 40));

        governmentButton.setBackground(new java.awt.Color(35, 36, 41));
        governmentButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        governmentButton.setForeground(new java.awt.Color(255, 255, 255));
        governmentButton.setText("Manage");
        governmentButton.setBorder(null);
        governmentButton.setFocusPainted(false);
        governmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                governmentButtonActionPerformed(evt);
            }
        });
        jPanel5.add(governmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 180, 40));

        jLabel23.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 102));
        jLabel23.setText("Orgnaization  ");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 320, 290));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons8-hospital-room-96.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 87));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Hospital ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 110, -1));

        hospitalButton.setBackground(new java.awt.Color(35, 36, 41));
        hospitalButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        hospitalButton.setForeground(new java.awt.Color(255, 255, 255));
        hospitalButton.setText("Manage");
        hospitalButton.setBorder(null);
        hospitalButton.setFocusPainted(false);
        hospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalButtonActionPerformed(evt);
            }
        });
        jPanel3.add(hospitalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 180, 40));

        jLabel24.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setText("Orgnaization  ");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 320, 290));

        exitLabel.setBackground(new java.awt.Color(255, 255, 255));
        exitLabel.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/logout white 50x50.png"))); // NOI18N
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitLabelMousePressed(evt);
            }
        });
        jPanel1.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 110, 120));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void hospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalButtonActionPerformed
        // TODO add your handling code here:
        HospitalEnterprise sy = new HospitalEnterprise(ecosystem, container);
        container.add(sy);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_hospitalButtonActionPerformed

    private void exitLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMousePressed
        // TODO add your handling code here:

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        //dB4OUtil.storeSystem(ecosystem);
        //DB4OUtil.dB4OUtil.storeSystem(ecosystem);
        //        container.remove(this);
//        Component[] componentArray = container.getComponents();
//        Component component = componentArray[componentArray.length - 1];
//        UserLogin manageSuppliersJPanel = (UserLogin) component;        
//        CardLayout layout = (CardLayout) container.getLayout();
//        layout.previous(container);
    }//GEN-LAST:event_exitLabelMousePressed

    private void nonProfitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonProfitButtonActionPerformed
        // TODO add your handling code here:
        NonProfitEnterprisse sy = new NonProfitEnterprisse(ecosystem, container);
        container.add(sy);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_nonProfitButtonActionPerformed

    private void pharmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmaButtonActionPerformed
        // TODO add your handling code here:
        PharmaEnterprises sy = new PharmaEnterprises(ecosystem, container);
        container.add(sy);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_pharmaButtonActionPerformed

    private void governmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_governmentButtonActionPerformed
        // TODO add your handling code here:
        GovernmentEnterprise sy = new GovernmentEnterprise(ecosystem, container);
        container.add(sy);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_governmentButtonActionPerformed

    private void emergencyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyButtonActionPerformed
        // TODO add your handling code here:
        EmergencyEnterprises sy = new EmergencyEnterprises(ecosystem, container);
        container.add(sy);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_emergencyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton emergencyButton;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JButton governmentButton;
    private javax.swing.JButton hospitalButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton nonProfitButton;
    private javax.swing.JButton pharmaButton;
    // End of variables declaration//GEN-END:variables
}
